User-agent: *
Disallow: /script/
Disallow: /console/
Disallow: /panel/
Disallow: /choose
Disallow: /*/faq.php
Disallow: /faq.php
Disallow: /*/about_us.php
Disallow: /about_us.php
Disallow: /*/dynamic.php
Disallow: /dynamic.php
Disallow: /*/audience.php
Disallow: /audience.php
Disallow: /*/payments.php
Disallow: /payments.php
Disallow: /*/meetus.php
Disallow: /meetus.php
Disallow: /*/campaign.php
Disallow: /campaign.php
Disallow: /*/analysis.php
Disallow: /analysis.php
Disallow: /*/customer.php
Disallow: /customer.php
Disallow: /*/formats.php
Disallow: /formats.php
Disallow: /*/themes.php
Disallow: /themes.php
Disallow: /*/statistics.php
Disallow: /statistics.php
Disallow: /*/editeurs.php
Disallow: /editeurs.php
Disallow: /*/infoslegales.php
Disallow: /infoslegales.php
Disallow: /*/annonceurs.php
Disallow: /annonceurs.php
Disallow: /*/modes_paiement.php
Disallow: /modes_paiement.php
Disallow: /downloadsv4/press/blackbook_(en).pdf
Disallow: /*/wall.php
Disallow: /wall.php
Disallow: /*/tac.html
Disallow: /tac.html
Disallow: /*/inscription.php
Disallow: /inscription.php
Disallow: /io/
