User-agent: *
Allow: /*s=p
Disallow: /*?
Disallow: /bin/
Disallow: /apps/
Disallow: /buy/
Disallow: /memberhome/
Disallow: /minisite/
Disallow: /products/
Disallow: /corporations/
Disallow: /buyers/
Disallow: /trade/
Disallow: /product/
Disallow: /catalogs/corporations/
Disallow: /catalogs/products/
Disallow: /rss/*/*.rss
Disallow: /activities/
Disallow: /productshowimg/
Disallow: /member/*/contactinfo.html
Disallow: /member/*/company_profile.html
Disallow: /member/*/productlist.html
Disallow: /newsuppliers/

User-agent: gomezagent
Disallow: /
User-agent: GomezAgent
Disallow: /
User-Agent: gomezagent+1.0
Disallow: /
User-Agent: GomezAgent+1.0
Disallow: /
User-Agent: gomezagent+2.0
Disallow: /
User-Agent: GomezAgent+2.0
Disallow: /
User-Agent: gomezagent+3.0
Disallow: /
User-Agent: GomezAgent+3.0
Disallow: /