Sitemap: http://www.booking.com/sitembk-index.xml
Sitemap: http://www.booking.com/sitembk-index-incr.xml
User-agent: psbot
Disallow: /
User-agent: TurnitinBot
Disallow: /
User-agent: NPBot-1/2.0
Disallow: /
User-agent: NPBot
Disallow: /
User-agent: *
Disallow: /honing.html
Disallow: /photo.html
Disallow: /photo.en.html
Disallow: /photo.de.html
Disallow: /photo.nl.html
Disallow: /photo.fr.html
Disallow: /photo.es.html
Disallow: /photo.it.html
Disallow: /photo.pt.html
Disallow: /photo.ja.html
Disallow: /photo.zh.html
Disallow: /photo.pl.html
Disallow: /book.html
Disallow: /mybooking.html
Disallow: /confirmation.html
Disallow: /reviewlist.*.html
Disallow: /navigation_times
Disallow: /hotelsonmap.*.json
Disallow: /general.*
Disallow: /markers_on_map 
Disallow: /logo
Disallow: /load_times
