#
# robots.txt
#
# v1.2, 6/17/2003

User-agent: *
Disallow: /pages/chase/ap/fundamentals/sbg
Disallow: /cm/cs?pagename=Chase/Href&urlname=chase/ap/fundamentals/sbg
Disallow: /pages/personal/sbg
Disallow: /cm/cs?pagename=Chase/Href&urlname=personal/sbg
Disallow: /pages/jpmorgan/cash
Disallow: /cm/cs?pagename=Chase/Href&urlname=jpmorgan/cash
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_home
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_keyfeatures
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_activation
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_faq
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_customer_support
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_device
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/mobile_termsofservice
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/sms_demo_pg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CMB_Mobsecurity
Disallow: /ccpmweb/shared/document/chase_mobile_card.pdf
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_home
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_keyfeatures
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_activation
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_faq
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_customer_support
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/CMB_device
Disallow: /ccp/index.jsp?pg_name=ccpmapp/cms/explore/page/mobile_termsofservice
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_home
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_learnmore
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_rates
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_apr
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_faqs
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_repay
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/private_loans/page/cpsl_contactus
Disallow: /ccp/index.jsp?pg_name=ccpmapp/student_loans/servicing/page/servicing_home
Disallow: /ccp/index.jsp?pg_name=ccpmapp/home_equity/shared/page/home_equity_wamu
Disallow: /ChaseCreditCard.html
Disallow: /k/
Disallow: /psmhelp/index.jsp?pg_name=shared/help/page/card_OrderConvChecks
Disallow: /psmhelp/index.jsp?pg_name=shared/help/page/card_OrderConvChecksConf
Disallow: /psmhelp/index.jsp?pg_name=shared/help/page/card_ConvenienceChecksConf
Disallow: /psmhelp/index.jsp?pg_name=shared/help/page/card_ConvenienceChecks
Disallow: /ccp/index.jsp?pg_name=shared/help/page/card_OrderConvChecks
Disallow: /ccp/index.jsp?pg_name=shared/help/page/card_OrderConvChecksConf
Disallow: /ccp/index.jsp?pg_name=shared/help/page/card_ConvenienceChecksConf
Disallow: /ccp/index.jsp?pg_name=shared/help/page/card_ConvenienceChecks
Disallow: /ccp/index.jsp?pg_name=ccpmapp/card_servicing/customer_service/page/faq_convcheck
Disallow: /ccp/index.jsp?pg_name=ccpmapp/individuals/checking/page/redirect_free_checking
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_74763
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_78994
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/offer-100-b
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/promo-WKM0000007205
Disallow: /ccp/index.jsp?pg_name=ccpmapp/smallbusiness/business_banking/page/bb_businessfree
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Checking_75Juneoffer_page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Checking_Student15_Page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/TriplePay_secure_Page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/promo-DZI0000007204
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/75_checking_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/ecoupon_50_promo3
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/78495_125ChkOffer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/marketing/page/test_global_header
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/test2oct25
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/56752ad
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/68126_Checking_Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/77997_125ChkOffer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Chase_Free_Checking_Offer2
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Chase_iPod
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Test_iPod_Page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Checking75Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/100_Bonus_Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/ecoupon_50_promo
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/ecoupon_50_promo2
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/ecoupon_promo
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_Offer1
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/rename_Offer-100
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/offer-100
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Offer-100-b_exp
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/rename_Offer-75
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/offer-75
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/glow_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/offer100_old
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/marketing/page/Test_iPod_Page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/cfc_75offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Chase_Free_Checking_Promo_Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/88865_gen_offer_blg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/caw/shared/page/chase_exclusiveschase_exclusives
Disallow: /ccp/index.jsp?pg_name=ccpmapp/chase_canada/choose_card_en/page/securemaster_cardfeatures_page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/chase_canada/choose_card_fr/page/ChaseGoldMC_details
Disallow: /ccp/index.jsp?pg_name=ccpmapp/chase_canada/home_en/page/rewardzonevisa_cardfeatures_dnu
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/thankyou_8685_exp
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/thankyou_8686_exp
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/thankyou_8718_exp
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/thankyou_8719_exp
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Account_Alert5_page
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Online_wire_xfer_old
Disallow: /ccp/index.jsp?pg_name=ccpmapp/spanish/creditcard/page/choose-card-expire
Disallow: /ccp/index.jsp?pg_name=ccpmapp/individuals/checking/page/Ecoupon_ChaseFreeChecking
Disallow: /ccp/index.jsp?pg_name=ccpmapp/individuals/checking/page/Ecoupon_Checking
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CFC_no_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/CFC_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/chasefreecheckingwdd
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/icon_no_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/icon_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/100_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/125_free_checking_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/48538_ad
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/65466a_freeckg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/65466b_freeckg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/65466c_freeckg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/65466d_freeckg
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/77427_xlob
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/cfc50_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Chase_Free_Checking_Offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/free_checking_630281
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/free_checking_630282
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/free_checking_631681
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_7476350
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/free_chkg_dd_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/no_offer_icon
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/offer-100
Disallow: /ccp/index.jsp?pg_name=ccpmapp/smallbusiness/business_banking/page/business_free_checkingOld
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/dso_8746
Disallow: /psmhelp/index.jsp?pg_name=ccpmapp/shared/help/page/dso_8746
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/48538_ad
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/48538_int
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/dso_8750
Disallow: /ccp/index.jsp?pg_name=ccpmapp/individuals/checking/page/free_checking
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_74763
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/marketing/page/Free_Checking_78994
Disallow: /psmhelp/index.jsp?pg_name=ccpmapp/shared/help/page/OLBP_Email_10_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/OLBP_Email_10_offer
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/help/page/dso_8746
Disallow: /online/auto-loan/car-loan.htm
Disallow: /online/Credit-Cards/credit-cards.htm
Disallow: /online/Credit-Cards/credit-cards.htm?card=member
Disallow: /credit-cards.htm?card=member
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/home_page/page/home-chase
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/home_page/page/home
Disallow: /chasehome.html
Disallow: /k_a_home.html
Disallow: /online/Home/banking-home.htm
Disallow: /online/Home/known-home.htm
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/home_page/page/home-chase
Disallow: /ccp/index.jsp?pg_name=ccpmapp/generic/home_page/page/home
Disallow: /online/Credit-Cards/credit-cards-at-chase.htm
Disallow: /online/Card-Servicing/card-servicing-home.htm
Disallow: /online/Credit-Cards/chase-credit-cards.htm
Disallow: /ccpmweb/card_servicing/document/credit-cards-home-known.html
Disallow: /online/Checking/Chase-Checking-Accounts.htm
Disallow: /online/Checking/Checking-Account.htm
Disallow: /online/Checking/Open-Chase-Checking-Accounts.htm
Disallow: /online/Checking/Open-Checking-Account.htm
Disallow: /banking-home.html
Disallow: /known-home.html
Disallow: /home-chase.html
Disallow: /chase-home.html
Disallow: /credit-cards-at-chase.html
Disallow: /card-servicing-home.html
Disallow: /chase-credit-cards.html
Disallow: /credit-cards-home-known.html
Disallow: /chase-checking-accounts.html
Disallow: /checking-account.html
Disallow: /open-chase-checking-accounts.html
Disallow: /open-checking-account.html
Disallow: /ccp/index.jsp?pg_name=ccpmapp/smallbusiness/home/page/business-banking
Disallow: /ccp/index.jsp?pg_name=ccpmapp/shared/assets/page/UltimateRewards_FAQ
Disallow: /index.jsp?pg_name=ccpmapp/shared/assets/page/UltimateRewards_FAQ
Disallow: /*swf*
Disallow: /content/
