User-agent: *
Disallow: /a/
Disallow: /activate
Disallow: /adminedit
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: */contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /group/terms/
Disallow: /internal/related/
Disallow: /json/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: /unauthorized_admin
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/

User-agent: Googlebot
Disallow: /a/
Disallow: /activate
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: */contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /internal/related/
Disallow: /group/terms/
Disallow: /json/
Disallow: */lang/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/

User-agent: Mediapartners-Google
Disallow: /a/
Disallow: /activate
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: */contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /internal/related/
Disallow: /group/terms/
Disallow: /json/
Disallow: */lang/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/

User-agent: Yandex
Disallow: /a/
Disallow: /activate
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: */contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /group/terms/
Disallow: /internal/related/
Disallow: /json/
Disallow: */lang/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/

User-agent: msnbot-media
Disallow: /a/
Disallow: /activate
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: /contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /group/terms/
Disallow: /json/
Disallow: /internal/related/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/

User-agent: Botify
Disallow: /a/
Disallow: /activate
Disallow: /adminedit
Disallow: /archived/
Disallow: /blog/
Disallow: */bookmark/
Disallow: */bookmarks/
Disallow: /commented/
Disallow: /comments/
Disallow: */contacts/
Disallow: */country/
Disallow: */created-after/
Disallow: /edit/
Disallow: */edited/
Disallow: /factory/
Disallow: /family_filter
Disallow: */featuredby/
Disallow: */get/
Disallow: /group/terms/
Disallow: /internal/related/
Disallow: /json/
Disallow: /logger/
Disallow: /masscast/
Disallow: /middle
Disallow: */mychannel/
Disallow: /onuser/
Disallow: /page/html/*
Disallow: /pageitem/
Disallow: /promote/
Disallow: */random/
Disallow: */rated/search/
Disallow: /register/activate
Disallow: */related/
Disallow: */relevance/search/
Disallow: /rss/
Disallow: */stag/
Disallow: */subscribedto/
Disallow: /tag/
Disallow: */tag/
Disallow: /tags/
Disallow: */tags/
Disallow: /&tid=generator
Disallow: /unauthorized_admin
Disallow: */unotes/
Disallow: /video/640x480
Disallow: /video/edit
Disallow: /video/video/
Disallow: */visited-hour/
Disallow: */visited/search/
Disallow: /widget_chunks/



Sitemap: http://www.dailymotion.com/map-regular.xml
Sitemap: http://www.dailymotion.com/map-videofull.xml
Sitemap: http://www.dailymotion.com/map-videolast.xml