User-agent: *
Disallow: /search.
Disallow: /search2.html
Disallow: /search3.html
Disallow: /ehow_radlinks_ads.html
Disallow: /admin/
Disallow: /services/
Disallow: /api/
Disallow: /users/
Disallow: /clips/

User-agent: bingbot
Disallow: /*?f=
Disallow: /search.
Disallow: /search2.html
Disallow: /search3.html
Disallow: /ehow_radlinks_ads.html
Disallow: /admin/
Disallow: /services/
Disallow: /api/
Disallow: /users/
Disallow: /clips/

User-agent: msnbot
Disallow: /*?f=
Disallow: /search.
Disallow: /search2.html
Disallow: /search3.html
Disallow: /ehow_radlinks_ads.html
Disallow: /admin/
Disallow: /services/
Disallow: /api/
Disallow: /users/
Disallow: /clips/

Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_1999_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2000_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2004_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2005_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2006_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2007_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2008_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2009_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_desktop_index_2010_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_1999_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2000_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2004_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2006_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2007_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2008_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2009_001.xml
Sitemap: http://www.ehow.com/sitemap_en-us_wap_index_2010_001.xml
