#
# robots.txt
#
User-agent: Googlebot
Disallow: /agreements/showdoc.aspx
Disallow: /Agreements/ShowDoc.aspx
Disallow: /app/
Disallow: /auctions/popups/
Disallow: /cds/widgets/popups/
Disallow: /chat/
Disallow: /deals/
Disallow: /Domains/Actions/
Disallow: /domains/actions/
Disallow: /Domains/Activate/Actions/
Disallow: /Domains/BulkSearch/Actions/JsonContent/
Disallow: /Domains/Controls/
Disallow: /domains/popups/
Disallow: /Domains/SearchResults/JsonContent/
Disallow: /eCommerce/Popups/
Disallow: /email/popups/
Disallow: /gdshop/app
Disallow: /gdshop/clo
Disallow: /gdshop/con
Disallow: /gdshop/for
Disallow: /gdshop/jump_pages/
Disallow: /gdshop/man
Disallow: /gdshop/mon
Disallow: /gdshop/ora
Disallow: /gdshop/par
Disallow: /gdshop/pay
Disallow: /gdshop/xt_
Disallow: /gdshop/yel
Disallow: /hosting/grid/popups/
Disallow: /hosting/hosting-plans.aspx
Disallow: /hosting/JsonContent/
Disallow: /hosting/jsoncontent/
Disallow: /Hosting/popups/
Disallow: /hosting/popups/
Disallow: /hosting/virtualdedserver/popups/
Disallow: /hosting/word-camp.aspx/
Disallow: /imag
Disallow: /jobs/
Disallow: /Jobs/
Disallow: /out
Disallow: /Popups/
Disallow: /popups/
Disallow: /reseller/popup/
Disallow: /sbs/
Disallow: /search-engine/popups/
Disallow: /ssl/Popups/
Disallow: /tube/
Disallow: /hdtube/
Disallow: /ViewExtensions/
Disallow: /WebProfessionalsDay09/
Disallow: /about/godaddy-chinese.aspx
Disallow: /Business/School/HowToMarketWebsite/Marketingyourwebsite.aspx
Disallow: /domains/get_a_website.aspx
Disallow: /domains/get_a_website_danica.aspx
Disallow: /domains/Get_A_Website_Exclusive.aspx
Disallow: /domains/get-a-website-Globe.aspx
Disallow: /domains/get-a-website-Globe-2.aspx
Disallow: /domains/search-ap2.aspx
Disallow: /domains/search-ca.aspx
Disallow: /domains/search-danica.aspx
Disallow: /domains/search-ella.aspx
Disallow: /domains/search-gl.aspx
Disallow: /domains/search-uk.aspx
Disallow: /domains/search-dus.aspx
Disallow: /domains/search-la.aspx
Disallow: /domains/search-hca.aspx
Disallow: /domains/search-danica2.aspx
Disallow: /gdshop/holiday/usmc2006.asp
Disallow: /gdshop/holiday/usmc2007.asp
Disallow: /gdshop/holiday/usmc2008.asp
Disallow: /gdshop/holiday/winter2006.asp
Disallow: /gdshop/mya_keepalive.asp
Disallow: /gdshop/offers/cross_sell.asp
Disallow: /gdshop/spamreport/spam_campaign_info.asp
Disallow: /gdshop/usmc.asp
Disallow: /gdshop/usmc_linkto.asp
Disallow: /holiday/usmc/usmc-2010.aspx
Disallow: /Holiday/usmc/usmc-2010.aspx
Disallow: /hosting/dedicatedserver/quote/printquote.aspx
Disallow: /hosting/hosting-technology.aspx
Disallow: /hosting/website-builder-featured-sites.aspx
Disallow: /icann/domain_search.aspx
Disallow: /legal/disclaimers.aspx
Disallow: /news/StatementSignUp.aspx
Disallow: /offers/cross-sell.aspx
Disallow: /offers/renewal-offer.aspx
Disallow: /parking/parking-details.aspx
Disallow: /prepayment/wiring.aspx
Disallow: /search/domains2-ella.aspx
Disallow: /search/domains-ap.aspx
Disallow: /search/search-ella.aspx
Disallow: /search/domains2.aspx
Disallow: /support/support-questions.aspx
Disallow: /tlds/mobilizer_blank.aspx
Disallow: /patent-notice.aspx
Disallow: /redeem/groupon.aspx
#
User-agent: *
Disallow: /agreements/showdoc.aspx
Disallow: /Agreements/ShowDoc.aspx
Disallow: /app/
Disallow: /auctions/popups/
Disallow: /cds/widgets/popups/
Disallow: /chat/
Disallow: /Domains/Actions/
Disallow: /domains/actions/
Disallow: /Domains/Activate/Actions/
Disallow: /Domains/BulkSearch/Actions/JsonContent/
Disallow: /Domains/Controls/
Disallow: /domains/popups/
Disallow: /Domains/SearchResults/JsonContent/
Disallow: /eCommerce/Popups/
Disallow: /email/popups/
Disallow: /gdshop/app
Disallow: /gdshop/clo
Disallow: /gdshop/con
Disallow: /gdshop/for
Disallow: /gdshop/jump_pages/
Disallow: /gdshop/man
Disallow: /gdshop/mon
Disallow: /gdshop/ora
Disallow: /gdshop/par
Disallow: /gdshop/pay
Disallow: /gdshop/xt_
Disallow: /gdshop/yel
Disallow: /hosting/grid/popups/
Disallow: /hosting/hosting-plans.aspx
Disallow: /hosting/JsonContent/
Disallow: /hosting/jsoncontent/
Disallow: /Hosting/popups/
Disallow: /hosting/popups/
Disallow: /hosting/virtualdedserver/popups/
Disallow: /hosting/word-camp.aspx/
Disallow: /imag
Disallow: /jobs/
Disallow: /Jobs/
Disallow: /out
Disallow: /Popups/
Disallow: /popups/
Disallow: /reseller/popup/
Disallow: /sbs/
Disallow: /search-engine/popups/
Disallow: /ssl/Popups/
Disallow: /hdtube/
Disallow: /tube/
Disallow: /ViewExtensions/
Disallow: /WebProfessionalsDay09/
Disallow: /Business/School/HowToMarketWebsite/Marketingyourwebsite.aspx
Disallow: /domains/get_a_website.aspx
Disallow: /domains/get_a_website_danica.aspx
Disallow: /domains/Get_A_Website_Exclusive.aspx
Disallow: /domains/get-a-website-Globe.aspx
Disallow: /domains/get-a-website-Globe-2.aspx
Disallow: /domains/search-ap2.aspx
Disallow: /domains/search-ca.aspx
Disallow: /domains/search-danica.aspx
Disallow: /domains/search-ella.aspx
Disallow: /domains/search-gl.aspx
Disallow: /domains/search-uk.aspx
Disallow: /domains/search-dus.aspx
Disallow: /domains/search-la.aspx
Disallow: /domains/search-hca.aspx
Disallow: /domains/search-danica2.aspx
Disallow: /gdshop/holiday/usmc2006.asp
Disallow: /gdshop/holiday/usmc2007.asp
Disallow: /gdshop/holiday/usmc2008.asp
Disallow: /gdshop/holiday/winter2006.asp
Disallow: /gdshop/mya_keepalive.asp
Disallow: /gdshop/offers/cross_sell.asp
Disallow: /gdshop/spamreport/spam_campaign_info.asp
Disallow: /gdshop/usmc.asp
Disallow: /gdshop/usmc_linkto.asp
Disallow: /holiday/usmc/usmc-2010.aspx
Disallow: /Holiday/usmc/usmc-2010.aspx
Disallow: /hosting/dedicatedserver/quote/printquote.aspx
Disallow: /hosting/hosting-technology.aspx
Disallow: /hosting/website-builder-featured-sites.aspx
Disallow: /icann/domain_search.aspx
Disallow: /legal/disclaimers.aspx
Disallow: /news/StatementSignUp.aspx
Disallow: /offers/cross-sell.aspx
Disallow: /offers/renewal-offer.aspx
Disallow: /parking/parking-details.aspx
Disallow: /prepayment/wiring.aspx
Disallow: /search/domains2-ella.aspx
Disallow: /search/domains-ap.aspx
Disallow: /search/search-ella.aspx
Disallow: /search/domains2.aspx
Disallow: /support/support-questions.aspx
Disallow: /tlds/mobilizer_blank.aspx
Disallow: /patent-notice.aspx
Disallow: /redeem/groupon.aspx
#
