User-Agent: *
Disallow: /*pgnew=
Disallow: /*_p=
Disallow: /*ucpg=
Disallow: /?f=
Disallow: /?lc= 
Disallow: /*&=&
Disallow: /*wa=wsignin1.0
Disallow: /*page=0
Disallow: /*page=&
Disallow: /*login.aspx
Disallow: /*&imageindex=0
Disallow: /*boardsparam=
Disallow: /*pollcontent=
Disallow: /*voteshowresults=
Disallow: /*pollid=
Disallow: /*jsdisabled
Disallow: /*mspperror
Disallow: /*msnrrhendler.aspx?
Disallow: /*msnrrhandler.aspx?
Disallow: /*MSNRRHandler.aspx?
Disallow: /*rss*/
Disallow: /*stub*.aspx?