User-agent: *
Sitemap: http://www.pornhub.com/sitemaps.xml
Disallow: *embed_player*
Disallow: *watch_player*
Disallow: *video_related*
Disallow: /users/
Disallow: /user/
Disallow: /photo/
Disallow: /albums/*-*
Disallow: /albums/*/*
Disallow: /album/
Disallow: *page*page*
Disallow: *search*o=*
Disallow: /rlock/
Disallow: /embed*
Disallow: *7urren*
Disallow: /wall_player_v2.php
Disallow: *player.php
Disallow: /xmoov_flv/player/index.php
Disallow: *player_v1.6b.swf
Disallow: /webmasters*
Disallow: /players/
Disallow: /front/
Disallow: *login=*
Disallow: /video/player_related_datas*
Disallow: *pkey=*
Disallow: *search*filter_category=*
Disallow: *search*filter_duration=*
Disallow: /iframe.php*
Disallow: /video/ajax_search_related*
Disallow: /video/ajax_video_related*
Disallow: /select/video/*
Disallow: *incategories*p=*
Disallow: /svvt/
Disallow: /playlist/rate*
Disallow: /video/pornstar_suggestion_list*
Disallow: *hd=1*
Disallow: /phubapi*
Disallow: /pornstars/search*
Disallow: /video/rate*