User-agent: *
User-agent: MJ12bot
Disallow: /...%20*
Disallow: /*...%20*
Disallow: /*aspxerrorpath*
Disallow: /*src=AF*
Disallow: /*src=CO*
Disallow: /blog/wp-content/
Disallow: /Catalogs/
Disallow: /catalogs/
Disallow: /Category.discounts/
Disallow: /category/*.aspx
Disallow: /Category/*.aspx
Disallow: /Community/
Disallow: /community/
Disallow: /compare/results.aspx
Disallow: /controlpanel/
Disallow: /controls/cms/
Disallow: /Coupon/Upload.aspx
Disallow: /Coupons/*.aspx
Disallow: /coupons/*.aspx
Disallow: /crossdomain.xml
Disallow: /Discounts_And_Coupons/
Disallow: /discounts_and_coupons/
Disallow: /fb-channel.html
Disallow: /frameset
Disallow: /Frameset
Disallow: /*rocery-*oupons.aspx/*oupons
Disallow: /images
Disallow: /Images
Disallow: /install/
Disallow: /Install/
Disallow: /join*
Disallow: /Join*
Disallow: /js/menu-categories.aspx
Disallow: /Login.aspx
Disallow: /login.aspx
Disallow: /members/
Disallow: /outclick.aspx
Disallow: /Outclick.aspx
Disallow: /pingback.aspx
Disallow: /Product*
Disallow: /product*
Disallow: /reactivate.aspx
Disallow: /rsscomments.aspx
Disallow: /sahpages/
Disallow: /search/*
Disallow: /sr.aspx
Disallow: /ShopAtHomeToolbarUninstall.exe
Disallow: /StoreReview.aspx
Disallow: /template*
Disallow: /toolbarframe.aspx
Disallow: /ToolbarFrame.aspx
Disallow: /toolbarprefs/
Disallow: /User*
Disallow: /user*
Disallow: /WebAPI/
Disallow: /webapi/
Disallow: /WebResource.axd
Disallow: /WILD*
Disallow: /Wild*
Disallow: /wild*
Disallow: /WishList*
Disallow: /wlwmanifest*
Disallow: /xd_receiver*
Disallow: */zip/*

User-agent: *
Allow: /Category/*/*.aspx
Allow: /category/*/*.aspx
Allow: /sahpages/Restaurant-Coupons.aspx
Allow: /sahpages/restaurant-coupons.aspx
Allow: /sahpages/Local-Coupons.aspx
Allow: /sahpages/local-coupons.aspx
Allow: /sahpages/Printable-Coupons.aspx
Allow: /sahpages/printable-coupons.aspx
Allow: /sahpages/Free-Stuff.aspx
Allow: /sahpages/free-stuff.aspx
Allow: /sahpage/free-samples.aspx
Allow: /sahpage/Free-Samples.aspx
Allow: /sahpages/about.aspx
Allow: /sahpages/end-user-license-agreement.aspx
Allow: /sahpages/privacy-policy.aspx
Allow: /sahpages/terms-and-conditions.aspx


User-agent: MJ12bot
Crawl-Delay:  3

User-agent: sogou spider
User-agent: YoudaoBot
User-agent: Spyfu
User-agent: Adbeat
Disallow: /

User-agent: AdsBot-Google
User-agent: MediaPartners-Google
Allow: /