User-agent: *
Disallow: /0
Disallow: /1
Disallow: /2
Disallow: /3
Disallow: /4
Disallow: /5
Disallow: /6
Disallow: /7
Disallow: /8
Disallow: /9
Disallow: /game/
Disallow: /search/
Disallow: /messages/
Disallow: /profile/
Disallow: /whoiknow/
Disallow: /unlimited/
Disallow: /helpdesk/
Disallow: /mailurl/
Disallow: /register/
Disallow: /backend/
Disallow: /photos/
Disallow: /facebook/
Disallow: /settings/
Disallow: /onlinemail/
Disallow: /unsubscribe/
Sitemap: http://www.twoocdn.com/static/4660350420004941983202093/sitemap.xml.gz