# /robots.txt 
User-agent: * 
Disallow: /cgi-bin 
Disallow: /fcgi-bin 
Disallow: /interact/photogallery/results.html 
Disallow: /interact/photogallery/details.html 
Disallow: /RealMedia 
Disallow: /search/partner 
Disallow: /search/enhancedlocalsearch 
Disallow: /search/sitesearch 
Disallow: /search/morelocations 
Disallow: /wx 
Disallow: /test 
Disallow: /search/morelocations 
Disallow: /print 
Disallow: /weather/print 
Disallow: /sponsored 
Disallow: /ugc 
Sitemap: http://www.weather.com/static/dru/sitemaps/domestic/en_US/news/sitemap-1.gz 
Sitemap: http://www.weather.com/static/dru/sitemaps/domestic/en_US/video/sitemap-1.gz
Sitemap: http://www.weather.com/static/dru/sitemaps/domestic/en_US/fixed/sitemap.gz 
Sitemap: http://www.weather.com/static/dru/sitemaps/domestic/en_US/location/sitemap.gz
