# robots.txt for www.wellsfargo.com
# Last generated Tue May  1 09:06:35 2001
User-agent: *
Disallow: /ads/
Disallow: /akamai/
Disallow: /auxiliary_access/
Disallow: /bop/
Disallow: /browser/
Disallow: /cgi/
Disallow: /com/ceo/iach.jhtml
Disallow: /com/ceo/upgrade
Disallow: /com/demos/
Disallow: /com/upgrade/
Disallow: /comp/
Disallow: /downloads/pdf/chinese/wachovia/news/wachovia_retail.pdf
Disallow: /downloads/pdf/chinese/wachovia/news/wellsfargo_retail.pdf
Disallow: /downloads/pdf/spanish/wachovia/news/wachovia_retail.pdf
Disallow: /downloads/pdf/spanish/wachovia/news/wellsfargo_retail.pdf
Disallow: /downloads/pdf/wachovia/checklist.pdf
Disallow: /downloads/pdf/wachovia/news/wachovia_investing.pdf
Disallow: /downloads/pdf/wachovia/news/wachovia_retail.pdf
Disallow: /downloads/pdf/wachovia/news/wachovia_securities.pdf
Disallow: /downloads/pdf/wachovia/news/wellsfargo_investing.pdf
Disallow: /downloads/pdf/wachovia/news/wellsfargo_retail.pdf
Disallow: /econ/
Disallow: /epayments_resources/
Disallow: /error/
Disallow: /featured_offers/
Disallow: /feedback/
Disallow: /funds/about_us/
Disallow: /funds/contact_us/
Disallow: /funds/fmg_fund/
Disallow: /funds/help/download/
Disallow: /funds/help/faqs/
Disallow: /funds/help/glossary/
Disallow: /funds/help/sitemap/
Disallow: /funds/login/
Disallow: /funds/logout/
Disallow: /funds/news/
Disallow: /funds/privacy/
Disallow: /funds/profile/
Disallow: /funds/quick_links/
Disallow: /funds/registration/
Disallow: /funds/sales/
Disallow: /funds/search/
Disallow: /funds/security/
Disallow: /funds/terms/
Disallow: /funds/tools/
Disallow: /images/
Disallow: /inatl/fx_newsletter
Disallow: /index_1.htm
Disallow: /investment_center/templates/
Disallow: /jump/
Disallow: /jump/deposits/official_checks
Disallow: /jump/wachovia/checking/college_checking
Disallow: /jump/wachovia/checking/free
Disallow: /jump/wachovia/savings_cds/cds
Disallow: /jump/wachovia/savings_cds/moneymarket
Disallow: /jump/wachovia/savings_cds/premium
Disallow: /jump/wachovia/savings_cds/way2save
Disallow: /lab/
Disallow: /lab/exit
Disallow: /lab/mortgage_widget
Disallow: /lab/terms
Disallow: /lab/thank_you
Disallow: /lab/what_widget
Disallow: /mwf/
Disallow: /pdf/
Disallow: /promo/
Disallow: /robots/
Disallow: /search/
Disallow: /seasonal/
Disallow: /spanish/wachovia/faqs/wachovia_services
Disallow: /spanish/wachovia/faqs/wellsfargo_services
Disallow: /spanish/wachovia/products_services
Disallow: /spanish/wachovia/welcome/
Disallow: /spanish/wachovia/welcome/billpay
Disallow: /spanish/wachovia/welcome/checkingsavings
Disallow: /spanish/wachovia/welcome/checkingsavings/faqs
Disallow: /spanish/wachovia/welcome/checklist/
Disallow: /spanish/wachovia/welcome/checklist/signup
Disallow: /spanish/wachovia/welcome/importantdates
Disallow: /special_offers/
Disallow: /tempcc/
Disallow: /util/
Disallow: /wachovia/biz/
Disallow: /wachovia/biz/atwork/
Disallow: /wachovia/biz/checkcard/
Disallow: /wachovia/biz/checking/
Disallow: /wachovia/biz/creditcards/
Disallow: /wachovia/biz/loans_lines/
Disallow: /wachovia/biz/membership/
Disallow: /wachovia/biz/merchant/
Disallow: /wachovia/biz/online_banking/
Disallow: /wachovia/biz/payroll/
Disallow: /wachovia/biz/premier/
Disallow: /wachovia/biz/savings/
Disallow: /wachovia/checkcard/
Disallow: /wachovia/checking/
Disallow: /wachovia/credit_cards/
Disallow: /wachovia/equity/
Disallow: /wachovia/faqs/wachovia_services
Disallow: /wachovia/faqs/wellsfargo_services
Disallow: /wachovia/giftcard/
Disallow: /wachovia/investing/retirement/destination_ira/
Disallow: /wachovia/news
Disallow: /wachovia/personal_credit/
Disallow: /wachovia/savings_cds/
Disallow: /wachovia/welcome/
Disallow: /wachovia/welcome/accountactivity/
Disallow: /wachovia/welcome/accountactivity/softwaresettings
Disallow: /wachovia/welcome/accountinfo/
Disallow: /wachovia/welcome/accountinfo/business/
Disallow: /wachovia/welcome/alerts/
Disallow: /wachovia/welcome/billpay/
Disallow: /wachovia/welcome/businesspayment/
Disallow: /wachovia/welcome/businesspayment/directpay
Disallow: /wachovia/welcome/checkingsavings/
Disallow: /wachovia/welcome/checkingsavings/faqs
Disallow: /wachovia/welcome/checklist/
Disallow: /wachovia/welcome/checklist/signup/
Disallow: /wachovia/welcome/checklist/signup/esign
Disallow: /wachovia/welcome/contact
Disallow: /wachovia/welcome/creditcard/
Disallow: /wachovia/welcome/creditcard/faqs
Disallow: /wachovia/welcome/importantdates/
Disallow: /wachovia/welcome/index1
Disallow: /wachovia/welcome/mobile/
Disallow: /wachovia/welcome/mortgage/
Disallow: /wachovia/welcome/transfers/
Disallow: /web_server_util/
Disallow: /wf/mortgage/rates
Disallow: /wfonline/station/access
Disallow: /wfonline/station/index
Disallow: /wfonline/station/receipts
Disallow: /wfonline/station/screensaver
Disallow: /wfonline/station/thankyou
Disallow: /wfonline/station/timeout
Disallow: /wizard/
Disallow: /xmlhome/
Disallow: /spanish/wachovia/colorado
Disallow: /wachovia/equity/index2 
Disallow: /wachovia/biz/loans_lines/specialized
Disallow: /biz/merchant/service/manage/associations/americanexpress
Disallow: https://labs.wellsfargo.com/vsafetestdrive/guest/testDrive.do
Disallow: /downloads/pdf/biz/merchant/amexregulations.pdf
Disallow: /downloads/pdf/biz/merchant/amexchanges.pdf
Disallow: /help/faqs/checking/overdraftservices
Disallow: /biz/help/faqs/checking/overdraftservices
Disallow: /wachovia/loans/welcome/index
Disallow: /wachovia/loans/welcome/payments
Disallow: /wachovia/loans/welcome/faqs
Disallow: /wachovia/loans/welcome/contact
Disallow: /wachovia/lines/welcome/index
Disallow: /wachovia/lines/welcome/payments
Disallow: /wachovia/lines/welcome/faqs
Disallow: /wachovia/lines/welcome/contact
Disallow: /wachovia/student/welcome/
Disallow: /wachovia/student/welcome/faqs
Disallow: /wachovia/student/welcome/contact
Disallow: /wachovia/mortgage/welcome/index
Disallow: /wachovia/mortgage/welcome/onlineaccess
Disallow: /wachovia/mortgage/welcome/escrowandtaxes
Disallow: /wachovia/mortgage/welcome/faqs
Disallow: /wachovia/mortgage/welcome/contactus
Disallow: /wachovia/private_bank/welcome
Disallow: /wachovia/credit_cards/welcome
Disallow: /wachovia/credit_cards/welcome/onlinebanking
Disallow: /wachovia/credit_cards/welcome/faqs
Disallow: /wachovia/credit_cards/welcome/contact
Disallow: /wachovia/welcomecenters
Disallow: /spanish/wachovia/welcomecenters
Disallow: /wachovia/welcome/brokerage
Disallow: /wachovia/wealthmanagement
Disallow: /wachovia/investing/index
Disallow: /wachovia/retirementpartners
Disallow: /wachovia/welcome/accountactivity/faq
Disallow: /wfonline/station/index.htm
Disallow: /wfonline/station/receipts.htm
Disallow: /wfonline/station/access.htm
Disallow: /wfonline/station/timeout.htm
Disallow: /wfonline/station/thankyou.htm
Disallow: /wfonline/station/screensaver.htm
Disallow: /retirementpartners
Disallow: /resourcecenter
Disallow: /wachovia/welcome/accountactivity/FAQ
Disallow: /wachovia/welcome/brokerage/
Disallow: /wachovia/welcome/billpay/faq
Disallow: /wachovia/welcome/billpay/pending-payments
Disallow: /about/corporate/legal/
Disallow: /about/corporate/legal/engagement
Disallow: /about/corporate/legal/billing
Disallow: /about/corporate/legal/expense
Disallow: /about/corporate/legal/invoicing
Disallow: /about/corporate/legal/contact
Disallow: /wfonline/issues
Disallow: /retirementplan/tools/savings-calculator
Disallow: /retirementplan/tools/401k-early-withdrawal-calculator
Disallow: /wfonline/wellsfargovsafe-enrollment
Disallow: /help/faqs/wellsfargovsafe
Disallow: /wfonline/tour/olb/auth_high_flash
Disallow: /spanish/wfonline/tour/olb/auth_high_flash
Disallow: /retirementplansite/penske
Disallow: /penske
Disallow: /biz/merchant/thank-you1
Disallow: /biz/merchant/thank-you2
Disallow: /biz/merchant/thank-you3
Disallow: /biz/merchant/thank-you4
Disallow: /biz/merchant/thank-you5
Disallow: /biz/merchant/thank-you6
Disallow: /biz/merchant/thank-you7
Disallow: /biz/merchant/thank-you8
Disallow: /biz/merchant/thank-you9
Disallow: /theprivatebank/contact1-thankyou
Disallow: /investing/styles/consultation1-thankyou
Disallow: /investing/retirement/consultation10-thankyou
Disallow: /investing/retirement/rolloverconsultation-thankyou 
Disallow: /theprivatebank/contact2-thankyou
Disallow: /investing/styles/consultation12-thankyou
Disallow: /investing/retirement/consultation11-thankyou
Disallow: /investing/retirement/rolloverconsultation1-thankyou
Disallow: /biz/merchant/thank-you