User-Agent: *
Allow: /$
Allow: /search/advanced$
Allow: /search/advanced/$
Allow: /images/$
Allow: /images/smart/$
Allow: /images/touch/$
Allow: /gorsel/$
Allow: /gorsel/smart/$
Allow: /gorsel/touch/$
Allow: /video/$
Allow: /video/touch/$
Disallow: /
